### ISSUE TITLE
ValueError: could not convert string to float: 

### ISSUE THREAD

**Issue by mengmanzbh** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#25]
Traceback (most recent call last):
  File "/Users/gsk/Desktop/LSTM-Neural-Network-for-Time-Series-Prediction/run.py", line 32, in <module>
    X_train, y_train, X_test, y_test = lstm.load_data('ok.csv', seq_len, True)
  File "/Users/gsk/Desktop/LSTM-Neural-Network-for-Time-Series-Prediction/lstm.py", line 23, in load_data
    result = normalise_windows(result)
  File "/Users/gsk/Desktop/LSTM-Neural-Network-for-Time-Series-Prediction/lstm.py", line 43, in normalise_windows
    normalised_window = [((float(p) / float(window[0])) - 1) for p in window]
ValueError: could not convert string to float:

**Comment by mengmanzbh** [comment]
why?

**Comment by singh-hrituraj** [comment]
It would be better if you could show a part of your dataset. For me it seems like that your inputs (or one of the input) contains string instead of a number. 

There could be various reasons for it. It can emanate from either a wrong value in Dataset or a wrong newline character in the data.
```python 
'\n'
```
This could have put a string into your dataset. I don't think it has anything to do with the code that has been presented here. It has to do with the preprocessing of your dataset which you will yourself have to do on your own.

**Comment by haggarw3** [comment]
you should check your data file and remove the columns that have before you can use your prediction model. If the data is categorical then you can check out this link for starters : 
https://www.datacamp.com/community/tutorials/categorical-data
