### ISSUE TITLE
LSTM prediction when time intervals are not fixed

### ISSUE THREAD

**Issue by VanitarNordic** [jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction#26]
Hello,

I have a dataset of raining time in a year. the dataset is something like this:

```
Time       Raining      Wind-speed         Temp
10            23           50               22
14            10           34               20
15             8           23               18

```
.......

magnitudes are just as an example. as you see time intervals are not fixed. I want to predict the next raining time by giving a previous time. But all examples I found about LSTM had fixed increasing time steps. for example 10,11,12,13,14 ...., such as stock market or sinus wave

But in my problem time steps are not fixed, but the time has an increasing rate. starts with a number and increases but the incident steps are not fixed. What should I do in these problems because I want to predict the next raining time

**Comment by Mandrewoid** [comment]
What you should do in this case is pad the data  in preprocessing. So in your example during time 11, 12, 13, if you don't have numbers because it isn't raining, you should fill it in with zeros. If it is raining, and you don't know how much you can fill it in either with interpolations from the known datapoints, or with an impossible number like -1. 

Unfortunately I think you're unlikely to have great predictions with missing data, but the best thing to do is just to experiment.

**Comment by VanitarNordic** [comment]
@Mandrewoid 

Actually the data is not missed because the raining happens in almost random timing pattern. 
if I put zero, -1 or whatever value in the empty fields or pads, then they will get a value when I scale them between 0 and 1, after applying fit_transform fro scikit. I have to scale the data before I could feed it to the LSTM.

**Comment by VanitarNordic** [comment]
I have another problem also. for padding I have to put the numpy array in a loop and fill the missed (or not raining) times which takes a quite reasonable time. as you know loops in python are quite slow.

**Comment by Mandrewoid** [comment]
Look at http://numba.pydata.org/ for accelerating your array manipulation loops.  Try doing the padding after the scaling. Do as much of your  Also if you pad with 0's, that is unaffected by scaling as 0 *n = 0
Do as much of your manipulation in numpy as possible because it will auto-parallelism when it can
